repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier-plugin-astro@^0.12.0
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.48.0"
    hooks:
      - id: eslint
        files: \.([jt]s|astro)$ # *.js, *.ts and *.astro
        types: [file]
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint
          - eslint-config-prettier
          - eslint-plugin-astro
          - eslint-plugin-unicorn
          - prettier@^3.0.2
          - prettier-plugin-astro@^0.12.0
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: "0.0.2"
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint
          - stylelint-config-standard-scss
