# This file is part of Share₂Fedi
# https://github.com/kytta/share2fedi
#
# SPDX-FileCopyrightText: © 2023 Nikita Karamov <me@kytta.dev>
# SPDX-License-Identifier: AGPL-3.0-only
name: Check and build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "^18.12.0"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm check
      - run: pnpm build
