# This file is part of Share₂Fedi
# https://github.com/kytta/share2fedi
#
# SPDX-FileCopyrightText: © 2023 Nikita Karamov <me@kytta.dev>
# SPDX-License-Identifier: AGPL-3.0-only
name: Deploy to Deno

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build --s2f-use-deno

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: share2fedi
          entrypoint: server/entry.mjs
          root: dist
