name: Deploy to Deno

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build --s2f-use-deno

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: share2fedi
          entrypoint: server/entry.mjs
          root: dist
